┌─────────────────────────────────┐         ┌───────────────────────────────┐
│             Categoria            │         │             Tarefa            │
├─────────────────────────────────┤         ├───────────────────────────────┤
│ - id: int                       │         │ - id: int                     │
│ - nome: string                  │         │ - nome: string                │
│ - userId: int                   │         │ - descricao: string?          │
│ - tarefas: Tarefa[]             │         │ - categoriaId: int            │
│                                 │         │ - user: User                  │
│                                 │         │                               │
│ + ... (outros campos e métodos) │         │ + ... (outros campos e métodos)│
└─────────────────────────────────┘         └───────────────────────────────┘
                  ▲                                         ▲
                  │                                         │
                  │                                         │
┌─────────────────┘                                         └───────────────────────┐
│                                                                                   │
│                                                                                   │
│                                       User                                        │
│                                                                                   │
│  ┌─────────────────────────────────┐         ┌───────────────────────────────┐    │
│  │             User                │         │             User              │    │
│  ├─────────────────────────────────┤         ├───────────────────────────────┤    │
│  │ - id: int                       │         │ - id: int                     │    │
│  │ - nome: string                  │         │ - nome: string                │    │
│  │ - categorias: Categoria[]       │         │ - categorias: Categoria[]     │    │
│  │                                 │         │                               │    │
│  │ + ... (outros campos e métodos) │         │ + ...(outros campos e métodos)│    │
│  └─────────────────────────────────┘         └───────────────────────────────┘    │
│                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────┘
