┌─────────────────────────────────┐         ┌───────────────────────────────┐         ┌───────────────────────────────┐      
│             User                │         │            Category           |         │             Task              |
├─────────────────────────────────┤         ├───────────────────────────────┤         ├───────────────────────────────┤
│ - id: String                    │         │ - id: Int                     │         │ - id: Int                     │
│ - name: String                  │         │ - name: string                │         │ - name: int                   │
│ - email: String                 │         │ - createdAt: DateTime         │         │ - description: int            │
│ - password: String              │         │ - updatedAt: DateTime         │         │ - createdAt: DateTime         │
│                                 │         │                               │         │ - updatedAt: DateTime         │
│ - tasks: Task[]                 │ <-----+ │ - tasks: Task[]               │ <-----+ │ - isPending: Boolean          │
└─────────────────────────────────┘         └───────────────────────────────┘         │                               │
                                                                                      | category: Category            |
                                                                                      |                               |
                                                                                      | user: User?                   |   
                                                                                      └───────────────────────────────┘                                                                                                     

